server:
  port: 8082
spring:
  datasource:
    password: 1234
    url: jdbc:postgresql://localhost:5431/notificacion
    username: nttdata
  jpa:
    database : POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
  zipkin:
    base-url: http://localhost:9411
  rabbitmq:
    addresses: localhost:5672
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true
    enabled: false
rabbitmq:
  exchanges:
    internal: internal.exchange
  queues:
    notification: notificacion.queue
  routing-keys:
    internal-notification: internal.notification.routing-key