apiVersion: apps/v1
kind: Deployment
metadata:
  name: autenticacion
  labels:
    app: autenticacion
spec:
  replicas: 1
  template:
    metadata:
      name: autenticacion
      labels:
        app: autenticacion
    spec:
      containers:
        - name: autenticacion
          image: christophermen/autenticacion:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8084
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: kube
      restartPolicy: Always
  selector:
    matchLabels:
      app: autenticacion
