server:
  port: 8081
spring:
  application:
    name: validarcliente
  datasource:
    password: 1234
    url: jdbc:postgresql://postgres:5432/clientecheck
    username: nttdata
  jpa:
    database : POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
  zipkin:
    base-url: http://zipkin:9411

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka
    fetch-registry: true
    register-with-eureka: true
    enabled: false