server:
  port: 8084
spring:
  datasource:
    password: 1234
    url: jdbc:postgresql://postgres:5432/autenticacion
    username: nttdata
  jpa:
    database : POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
  zipkin:
    base-url: http://zipkin:9411

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka
    fetch-registry: true
    register-with-eureka: true
#    enabled: false

jwt:
  secret: secret

admin-paths:
  paths:
    - uri: "/api/v1/cliente"
      method: "POST"
    - uri: "/api/v1/cliente"
      method: "PUT"
    - uri: "/api/v1/cliente/{1}[1-9]+[0-9]*"
      method: "DELETE"
    - uri: "/api/v1/cliente-check/{1}[1-9]+[0-9]*"
      method: "GET"